user = {
  name: "Harrison Buford",
  followers: 523,
  following: 7,
  favorites: [],
  location: "Hog Wallow, KY",
  email: "hbuford34@aol.com",
  website: "harrisonisawesome34.com",
  twitter: "",
  highlights: [],
  organizations: [],
  repositories: [{
    id: 1,
    name: "greys-anatomy-lorem-ipsum-generator",
    description: "A lorem ipsum generator with medical terms and words from the show Grey's Anatomy.",
    tags: ["netlify", 'jamstack', 'lorem-ipsum-generator', 'medical', 'serverless', 'react'],
    language: "JavaScript",
    favorites: 8,
    forks: 3,
    license: "",
    issues: 1,
    timestamp: new Date(2024, 0, 29, 22, 21, 43, 32),
    star: false,
  }, {
    id: 2,
    name: "how-many-days-until",
    description: "A React countdown app of days between today and next year.",
    tags: ['react', 'countdown', 'hacktoberfest'],
    language: "JavaScript",
    favorites: 6,
    forks: 33,
    license: "",
    issues: 0,
    timestamp: new Date(2024, 0, 13, 8, 55, 55, 0),
    star: false,
  }, {
    id: 3,
    name: "httriri",
    description: "HTTRiRi - HTTP Status Codes as Portrayed by Rihanna GIFs",
    tags: ['http', 'status-codes', 'gifs', 'rihanna', 'hacktoberfest'],
    language: "TypeScript",
    favorites: 37,
    forks: 22,
    license: "",
    issues: 4,
    timestamp: new Date(2024, 1, 6, 17, 45, 9, 0),
    star: false,
  }, {
    id: 4,
    name: "ambition-fund-website",
    description: `Website for www.ambitionfund.org, micro-grant program to provide support for underrepresented 
                  people who need financial assistance pursuing professional development opportunities in the technology sector.`,
    tags: ['donation', 'landing-page'],
    language: "JavaScript",
    favorites: 7,
    forks: 6,
    license: "MIT License",
    issues: 3,
    timestamp: new Date(2022, 1, 1, 2, 32, 1, 78),
    star: false,
  }
],
  projects: [],
  packages: []
}
